version: '2'
services:

  server:
    build: .
    ports:
     - 8080
    environment:
     - ZK_CONNECTION_STRING=zookeeper:2181
    depends_on:
    - zookeeper

  zookeeper:
    image: zookeeper:latest

  loadbalancer:
    image: dockercloud/haproxy
    links:
      - server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
