version: '2'
services:

  server:
    build: .
    ports:
     - 8080
    environment:
     - ZK_CONNECTION_STRING=zookeeper:2181
    depends_on:
    - zookeeper

  zookeeper:
    image: zookeeper:latest
